export const state = [
  { value: 'Andhra Pradesh', key: 'AP' },
  { value: 'Arunachal Pradesh', key: 'AR' },
  { value: 'Assam', key: 'AS' },
  { value: 'Bihar', key: 'BR' },
  { value: 'Chhattisgarh', key: 'CT' },
  { value: 'Goa', key: 'GA' },
  { value: 'Gujarat', key: 'GJ' },
  { value: 'Haryana', key: 'HR' },
  { value: 'Himachal Pradesh', key: 'HP' },
  { value: 'Jharkhand', key: 'JH' },
  { value: 'Karnataka', key: 'KA' },
  { value: 'Kerala', key: 'KL' },
  { value: 'Madhya Pradesh', key: 'MP' },
  { value: 'Maharashtra', key: 'MH' },
  { value: 'Manipur', key: 'MN' },
  { value: 'Meghalaya', key: 'ML' },
  { value: 'Mizoram', key: 'MZ' },
  { value: 'Nagaland', key: 'NL' },
  { value: 'Odisha', key: 'OR' },
  { value: 'Punjab', key: 'PB' },
  { value: 'Rajasthan', key: 'RJ' },
  { value: 'Sikkim', key: 'SK' },
  { value: 'Tamil Nadu', key: 'TN' },
  { value: 'Telangana', key: 'TS' },
  { value: 'Tripura', key: 'TR' },
  { value: 'Uttar Pradesh', key: 'UP' },
  { value: 'Uttarakhand', key: 'UK' },
  { value: 'West Bengal', key: 'WB' },
];
